### ISSUE TITLE
Document Profile Page Requirements

### ISSUE THREAD

**Issue by mertcan-ozkan** [bounswe/bounswe2022group3#24]
Requirements for profile page for users shall be identified  from the profile description.  They will be documented on [Requirements page](https://github.com/bounswe/bounswe2022group3/wiki/Requirements).

Deadline: 13.03.22 -23.59
Reviewer: @muhammetssen  
Review Deadline: 14.03.22

**Comment by mertcan-ozkan** [comment]
The first drft  for the system requirements- profile page [added](https://github.com/bounswe/bounswe2022group3/wiki/Requirements/_edit).
This section of the requirements will be modified according to user requirements and meeting in 16.03.2022.

**Comment by mertcan-ozkan** [comment]
First draft has been reviewed by the team members. This section of the requirements will be modified according to user requirements and the meeting in 16.03.2022. New issue will be opened for this topic.

**Comment by muhammetssen** [comment]
- I think we should use `learner` instead of `student` and `lecturer` instead of `teacher` for the sake of convenience.
- I think there is a typo in 2.1.1.2.3.1. I could not understand what `interest’s section` is.
- 2.1.1.2.4.2 could be improved by specifying the visibility of the profile page. If the profile is public, one does not have to follow to see activities.
- Achievements section could be a subsection of Activities tab since they are dependent and we do not use achievements in somewhere else. 
- I could not understand why we are not showing progresses of students to followers. 2.1.1.2.5.4
- We could add a lot more to 2.1.1.3.2.1 like courses, education life, years of experience etc.
- Why learners can edit lecturers' profiles? 2.1.2.1
- Similarly, is following a necessity to see someone's activities if the profile is already public? 2.1.2.2.4.2
- I could not understand the sentence 2.1.2.3.2
@mertcan-ozkan

**Comment by mertcan-ozkan** [comment]
Articles 1-2-5 are fixed. Several typos are fixed. The rest of the reviews will be addressed in a diffrenet issue after the meeting in 16.03.2022.
