### ISSUE TITLE
Writing User Scenario #1

### ISSUE THREAD

**Issue by ersoykadir** [bounswe/bounswe2022group3#37]
The User Scenario 1 will be written as stated in week 3 [meeting notes](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%234-18.03.2022). 

Reviewer: @mertcan-ozkan 
Deadline 21.03.2022 23:59

**Comment by ersoykadir** [comment]
First draft is on [scenario#1](https://github.com/bounswe/bounswe2022group3/wiki/Scenario-1). Needs to be reviewed.

**Comment by mertcan-ozkan** [comment]
- Scenario, Actions - article 4 -there is a small typo in the last sentence: "current" 
- I think a new article should be added to "Scenario, Actions" since learners should be able to notify the lecturer if they  will join the event. This is not explictly exlained here. I think the lecturer should collect the attendence after posting the event.
- I think the lecturer should also tell the students that this event will have an entrence fee. I think this should also be explained when the lecturer creates an event.
- I think we should also say that the lecturer may decide to cancel the event if there is not enough attendence. This is included in acceptance criteria but not explictly in Scenario, Actions.
- In Acceptance Criteria : 
Users shall be able to join the attendance list of the event  that they would like to participate.
In this sentence I think we should add that to join the attendence:
Learner should be enrolled in the course.
Lecturer should be giving the course.

**Comment by ersoykadir** [comment]
> * I think a new article should be added to "Scenario, Actions" since learners should be able to notify the lecturer if they  will join the event. This is not explictly exlained here. I think the lecturer should collect the attendence after posting the event.
- I presumed that the system would handle the notifications when a learner joins to the event, also would provide the lecturer the list of people who will attend. Since the scenario is from the perspective of the lecturer, I am avoiding these details.
> * I think the lecturer should also tell the students that this event will have an entrence fee. I think this should also be explained when the lecturer creates an event.
- Entrance fee option will be stated when creating an event and the event will be have a badge or an explicit note on the UI, implying that event is not free. These should have been stated in requirements of the project but it is missing for some reason. I am opening an [issue]() for it.
> * I think we should also say that the lecturer may decide to cancel the event if there is not enough attendence. This is included in acceptance criteria but not explictly in Scenario, Actions.
- I finished the scenario after lecturer created the event, not including the results of the event in the scenario. I think including this as an acceptance criteria is enough.
> * In Acceptance Criteria :
>   Users shall be able to join the attendance list of the event  that they would like to participate.
>   In this sentence I think we should add that to join the attendence:
>   Learner should be enrolled in the course.
>   Lecturer should be giving the course.
- Added "Learner should be enrolled in the course." to acceptance criterias. The lecturer part is implicitly stated since learner can't enroll in a non-existent class event.
> * Acceptance Criteria -I think we should add that lecturer of a course should be able to create a poll, allowed to be filled by the students enrolled in the course.
- Added to acceptance criteria.

**Comment by mertcan-ozkan** [comment]
After the reviews and editings, the scenerio 1 is completed.
