### ISSUE TITLE
Changing the User Part in the Requirements

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2022group3#63]
Draft in issue #60 is accepted in the weekly meeting. This issue is for tracking on the changes that will be made. 
Deadline: 02/04/2022 - 23.59
Reviewer: @muhammetssen

**Comment by Brunettow** [comment]
First draft is added [here](https://github.com/bounswe/bounswe2022group3/wiki/Requirements-(New-Version))
What is changed?
- Lecturer and Learner parts are deleted
- Search engine part moved to the system requirements
- Changing requirements that contains phone (We decided to not use any operations via phones.)

What can be changed?
- Profile part in system requirements and in user can be reviewed and can be unified.

**Comment by muhammetssen** [comment]
@brunettow and I reviewed the changes in User Requirements 
and Search Engine. We have made some minor changes like fixing typos, re-orderings etc.

## User 
Reconsturcted the general structure of the user requirements. 
- Moved block and follow actions to 1.3 User Actions tab.
- Created a subsection for users who have created a course.
## Search Engine
- 2.5.4 What should be the criteria for sorting according to date? We could first show newest or oldest post. Moreover, should we use created or last updated date?
- 2.5.3.* What is normal?
- Do we need to rate users according to their teaching performance? 
- 2.5.7.2 What is the meaning of `topic`? 1.3.8 has a different meaning for it.

Further review is needed for System Requirements.

**Comment by bilalcim** [comment]
> * 2.5.2.* What is normal?

That is a good point. I thought behind all of the options such as ranking with respect to
* similar interest,
* relevant background,
* or background/interest of one's friends,

that there would be some default ranking but, then again, what should be the "default ranking"?

**Comment by nurlandadashov02** [comment]
Reviewed the current state of the user requirements. Below are my suggestions:

1. 1.1.1.1. Should be split into two. The first part of the current sentence represents the custom authentication system that we are going to build, while the second part is the social signup feature where we are going to use APIs provided by the respective companies. Current 1.1.1.2 can be moved under  1.1.1.1. since it is related to the first type of sign-up.
     *  1.1.1.1. Users shall be able to register using a valid and unique email address, a username, and a password as defined in the security section.
         *  1.1.1.1.1. Users who are registered by providing their emails shall confirm their accounts via clicking the link sent in the confirmation email.
     *  1.1.1.2. Users shall be able to register using their Facebook, Twitter, Google account.
2. 1.1.2.1. can be split:
    * Users shall be able to log into their account using their email and password combination or via 
    * Users shall be able to log into their account using their Facebook, Twitter, Google account (if they have previously completed 1.1.1.2.).
3. We should add Logout requirement to 1.1
4. Maybe we could elaborate more on 1.3.1 and 1.3.2. In other parts, we are giving references to other sections.  Something similar can be done here, or we provide more details by creating sub requirements

**Comment by ersoykadir** [comment]
Should we include an 
- "Users shall agree to the Terms of Service and Privacy Policy to finish registering." 

or something similar to that on section 1.1.1 Registration?

**Comment by nurlandadashov02** [comment]
> Should we include an article like,
> 
> * "Users shall agree to the Terms of Service and Privacy Policy to finish registering."
> 
> or something similar to that on section 1.1.1 Registration?

@ersoykadir This also came to my mind, however since there is `3.3.2. Users shall agree to the Terms of Service and Privacy Policy while registering.` in non-functional requirements, I did not think we should duplicate it.

**Comment by ersoykadir** [comment]
> > Should we include an article like,
> > 
> > * "Users shall agree to the Terms of Service and Privacy Policy to finish registering."
> > 
> > or something similar to that on section 1.1.1 Registration?
> 
> @ersoykadir This also came to my mind, however since there is `3.3.2. Users shall agree to the Terms of Service and Privacy Policy while registering.` in non-functional requirements, I did not think we should duplicate it.

I think `3.3.2. Users shall agree to the Terms of Service and Privacy Policy while registering.` is not a Non-functional requirement, we should move it to functional side.

**Comment by hsuleerkul** [comment]
Currently Achievements are only defined under 2.2. Profile Page; however, I think it needs to have its own section for the following reason: Each course - learner pair needs a seperate `Achievements` section to keep a user's progress on only that course and store the gained badges of that particular course.

**Comment by muhammetssen** [comment]
> Currently `Achievements` are only defined under 2.2. Profile Page; however, I think it needs to have its own section for the following reason: Each course - learner pair needs a seperate `Achievements` section to keep a user's progress on only that course and store the gained badges of that particular course.

We will use `Enrollment` class to store all the related information between a user and a course, like progress and notes #88. 
However, I could not fully understand why we should separate achievements by courses. For example, a note is directly connected to a course but an achievement is a property of the user. 

I agree that  `Achievements` needs its own section. I was expecting to see much more detail while designing enrollment class. @hsuleerkul

**Comment by mertcan-ozkan** [comment]
I think several articles in the user requirements can be modified so that requirements page compasses this use case diagram fully -[Use Case - "View Profile, Edit Profile"](https://github.com/bounswe/bounswe2022group3/issues/80#):
*1.2.3. Users shall be able to modify their personal information if they want to.- I think this sentence should be changed into : Users shall be able to modify **and view** their personal information if they want to.
*It seems that monitoring section is missing from the user requirements. A small senctence can be added to include this section:   -"Users shall be able monitor their performence for each course they attend to."
*Also I think articles 1.2.5. and 1.2.6. can be merged together. I think there is no reason for them to be seperated.

**Comment by salimtirit** [comment]
We have discussed this issue in our meeting in [04-Apr-2022](https://github.com/bounswe/bounswe2022group3/wiki/Meeting-Notes-%237-04.04.2022). We have resolved this issue. Here are the things we did:

- Fixed typo in requirement 1.1.2.1
- Rephrased requirement 1.1.2.3
- We added a log-out requirement (see requirements 1.1.3 and 1.1.3.1)
- We added references to requirements 1.3.1 and 1.3.2
- We changed the profile and user actions in user requirements (1.2, 1.3.9 and 1.3.10 )
