### ISSUE TITLE
Class Diagram - Overlap of Enrollment and Achievements Classes

### ISSUE THREAD

**Issue by muhammetssen** [bounswe/bounswe2022group3#97]
# Description
As of now, first drafts of enrollment #88 and achievemet #72 both tries to cover progress tracking. They are also similar in structure since they both connect user and course classes. We should design a better structure that provides isolation and solves overlaps between two classes.

@hsuleerkul and I will have a discussion in person regarding this issue. We will add action items below as a comment to this page.

**Deadline:** 05.04.2022 11.00

**Comment by hsuleerkul** [comment]
We have completed our discussion. Here are our discussion notes and action items. 

# Discussion Notes
- There will be 2 kinds of badges:
    1. System will have a predefined list of badges like:
        - You have completed 5 courses
        - You have created your first course
        - You have created a discussion
        - You got a rating above 4/5
    2. Course lecturer will be able to create new badges to specific chapters and users will gain those as they progress throughout the course. We must add new requirements for this case.
        - When a user completes a chapter, enrollment class will be responsible for finding the badge for that chapter and add it to that user's personal information instance.
- Enrollment class will be updated in order to have a proper progress tracking system. User will indicate that they completed the chapter. This action will be captured by Chapter class. Then, enrollment class will be responsible for processing this action.

# Action Items
- Achievement class will be replaced with Badge class
- Requirement 2.1.2.2.2 will be updated as:
        `System shall keep a predefined list of badges that can be earned by user such as completing a course, opening a new course, receiving a rating that is greater than 4 out of 5.(see 2.1.2.7.2.) `

- Requirement 2.1.2.2.3 will be updated as:
       ` System shall provide course lecturers an interface for creating custom badges when they are creating new chapters. System will reward the users who complete spesified chapters with corresponding custom badges.`

This issue will be closed and progress wil be kept under issue #88 and issue #99
